"""Serial HTTP transport only. Model and decisions reside in robot.exe."""
import argparse
import json
import queue
import subprocess
import sys
import threading
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'vendor'))
from mocksim.client import RobotClient, Rejected, TransportFailure, ProtocolError


def _until(fn, deadline_at):
    """Bound the whole operation, including a stalled HTTP body or child pipe.

    A timed-out worker may still be receiving its old response. The caller must
    abort the run without sending any new action (including /exit) in that case.
    """
    remaining = deadline_at - time.perf_counter()
    if remaining <= 0:
        raise TimeoutError('real deadline: incomplete run')
    result = queue.Queue(maxsize=1)
    def work():
        try:
            result.put((True, fn()))
        except Exception as exc:
            result.put((False, exc))
    threading.Thread(target=work, daemon=True).start()
    try:
        ok, value = result.get(timeout=max(0, deadline_at-time.perf_counter()))
    except queue.Empty:
        raise TimeoutError('real deadline during operation: incomplete run') from None
    if not ok:
        raise value
    return value


class DeadlineClient(RobotClient):
    """Reuse original serialization/logging, but cap every attempt and retry.

    New IDs are still generated by RobotClient action methods. All retries call
    its post() with the identical payload. Only one request is in flight.
    """
    deadline_at = float('inf')

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.retry_limit = self.retries
        self.retries = 0  # Remain zero even if an old worker outlives its deadline.
        self.aborted = False

    def _position_action(self, kind, x, y, channel):
        # Preserve the exact binary64 coordinate received from robot stdout.
        # Original RobotClient._num rounds to 1e-6 m, which can invalidate a
        # closed angular boundary in a strict set-membership calculation.
        payload = self._base(kind)
        payload.update(position={'x':float(x), 'y':float(y)}, channel=int(channel))
        return self.post('/'+kind, payload)

    def measure(self, x, y, channel):
        return self._position_action('measure', x, y, channel)

    def clear(self, x, y, channel):
        return self._position_action('clear', x, y, channel)

    def post(self, path, payload):
        if self.aborted:
            raise TimeoutError('run already aborted with an uncertain request')
        timeout, retry_limit = self.timeout_s, self.retry_limit
        try:
            for attempt in range(retry_limit + 1):
                remaining = self.deadline_at-time.perf_counter()
                if remaining <= 0:
                    raise TimeoutError('real deadline before request: incomplete run')
                self.timeout_s = min(timeout, remaining)
                try:
                    if self.deadline_at == float('inf'):
                        response = super().post(path, payload)
                    else:
                        response = _until(lambda: super(DeadlineClient, self).post(path, payload), self.deadline_at)
                    status = self.log[-1]['http_status']
                    if status != 200:
                        raise ProtocolError(status, response)
                    return response
                except TransportFailure:
                    if attempt == retry_limit:
                        raise
                    delay = self.retry_backoff_s*(attempt+1)
                    remaining = self.deadline_at-time.perf_counter()
                    if remaining <= delay:
                        raise TimeoutError('real deadline before retry: incomplete run') from None
                    self.stats.retries += 1
                    time.sleep(delay)
        except TimeoutError:
            self.aborted = True
            raise
        finally:
            self.timeout_s = timeout


def drive(problem, client, early=35, deadline=1200, position_error=0.0, planner_depth=2, strategy='joint'):
    if strategy not in ('geometric','joint','previous','stage1','stage2','baseline'):
        raise ValueError('strategy must be geometric, joint, previous, stage1, stage2 or baseline')
    if type(planner_depth) is not int or not 0 <= planner_depth <= 3:
        raise ValueError('planner depth must be an integer in [0,3]')
    if not 0 <= position_error <= .4:
        raise ValueError('position error must be in [0, 0.4] metres')
    start = time.perf_counter()
    hard_stop = start + deadline
    def call(fn, cutoff):
        if isinstance(client, DeadlineClient):
            client.deadline_at = cutoff
            return fn()
        return _until(fn, cutoff)
    enter = call(client.enter, hard_stop)
    if enter.get('accepted') is not True:
        raise Rejected(enter)
    # Start-based accounting is conservative about time spent receiving /enter.
    hard_stop = start + min(deadline, enter['remaining_real_duration_s'])
    remaining = hard_stop-time.perf_counter()
    if remaining <= 0:
        raise TimeoutError('no real duration remains after enter: incomplete run')
    action_stop = hard_stop-min(2.0, remaining*.1)
    proc = subprocess.Popen([str(ROOT / 'robot.exe'), str(problem), str(early), str(position_error), str(planner_depth), strategy],
                            stdin=subprocess.PIPE, stdout=subprocess.PIPE,
                            stderr=subprocess.PIPE, text=True, bufsize=1)
    virtual, final = 0, None
    lines = queue.Queue()
    errors = []
    def read_output():
        try:
            for line in proc.stdout:
                lines.put(line)
        finally:
            lines.put(None)
    def read_errors():
        for line in proc.stderr:
            errors.append(line)
    reader = threading.Thread(target=read_output, daemon=True)
    err_reader = threading.Thread(target=read_errors, daemon=True)
    reader.start(); err_reader.start()
    try:
        while True:
            # Safe /exit only between completed actions, never after an uncertain
            # timed-out request, which might still be registered on the server.
            remaining = action_stop-time.perf_counter()
            if remaining <= 0:
                final = call(client.exit, hard_stop)
                raise TimeoutError('real deadline guard: incomplete run')
            try:
                line = lines.get(timeout=remaining)
            except queue.Empty:
                final = call(client.exit, hard_stop)
                raise TimeoutError('solver output deadline: incomplete run') from None
            if line is None:
                raise RuntimeError('solver exited without certificate: ' + ''.join(errors))
            if virtual >= 359900:
                final = call(client.exit, hard_stop)
                raise TimeoutError('virtual deadline guard: incomplete run')
            fields = line.split()
            if fields[0] == 'exit':
                final = call(client.exit, hard_stop)
                if final.get('accepted') is not True:
                    raise Rejected(final)
                return dict(cleared=int(fields[1]), certificate=fields[2],
                            planner_depth=planner_depth if position_error == 0 else 0,
                            strategy=strategy if position_error==0 and planner_depth>0 else 'legacy',
                            virtual_time_s=final['virtual_time_s'],
                            runtime_s=time.perf_counter()-start, response=final)
            action, channel, x, y = fields
            if action not in ('measure', 'clear'):
                raise ValueError('unknown solver action')
            response = call(lambda: getattr(client, action)(float(x), float(y), int(channel)), action_stop)
            if response.get('accepted') is not True:
                raise Rejected(response)
            virtual = response['virtual_time_s']
            if action == 'measure':
                kind = {'no_signal': 0, 'near': 1, 'direction': 2}[response['measure_result']]
                reply = f"{kind} {response.get('svd_deg', 0)}\n"
            else:
                reply = f"{int(response['clear_result'] == 'success')}\n"
            proc.stdin.write(reply)
            proc.stdin.flush()
    finally:
        if proc.poll() is None:
            proc.terminate()
        proc.wait(timeout=5)
        reader.join(timeout=1)
        err_reader.join(timeout=1)
        for stream in (proc.stdin, proc.stdout, proc.stderr):
            stream.close()


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--problem', type=int, choices=[3,4], required=True)
    p.add_argument('--team-id', required=True)
    p.add_argument('--url', default='http://127.0.0.1:2026')
    p.add_argument('--log', required=True)
    p.add_argument('--early', type=float, default=35)
    p.add_argument('--position-error', type=float, default=0.0)
    p.add_argument('--strategy', choices=['geometric','joint','previous','stage1','stage2','baseline'], default='joint')
    p.add_argument('--planner-depth', type=int, choices=[0,1,2,3], default=2,
                   help='0: previous controller; 1/2/3: receding-horizon decision depth (default 2)')
    a = p.parse_args()
    # This program never launches or purchases a formal test session.
    with open(a.log, 'x', encoding='utf-8') as f:
        def log(row):
            f.write(json.dumps(row, ensure_ascii=False) + '\n')
            f.flush()
        client = DeadlineClient(base_url=a.url, robot_id=a.team_id, log_sink=log)
        result = drive(a.problem, client, a.early, position_error=a.position_error, planner_depth=a.planner_depth, strategy=a.strategy)
    print(json.dumps(result, ensure_ascii=False, indent=2))

if __name__ == '__main__':
    main()
