"""Materialize readable native adapters from the unchanged reviewed reference.

Only the two sparse-expression loop bodies are replaced in the LP builders.
The M1 class keeps its state law and substitutes the native PL convolution.
"""
from pathlib import Path
import ast,hashlib,json
R=Path(__file__).resolve().parent;S=R.parent/'src'

def node_text(path,name):
    source=path.read_text();tree=ast.parse(source)
    node=next(n for n in tree.body if isinstance(n,(ast.FunctionDef,ast.ClassDef)) and n.name==name)
    return '\n'.join(source.splitlines()[node.lineno-1:node.end_lineno])+'\n'

def replace_nested(text,name,replacement):
    node=next(n for n in ast.walk(ast.parse(text)) if isinstance(n,ast.FunctionDef) and n.name==name)
    lines=text.splitlines();lines[node.lineno-1:node.end_lineno]=replacement.splitlines();return '\n'.join(lines)+'\n'

legacy=node_text(S/'control.py','affine_plan').replace('def affine_plan(', 'def legacy_affine_plan(',1)
legacy=replace_nested(legacy,'expr', '''    def expr(which):
        if not affine:
            raise ValueError('Native planner adapter supports the registered affine policy only')
        energy = np.stack((err, ema), axis=2)
        previous = np.stack((avg, ema), axis=2)
        intercept, gain = {'Q': (aq, gq), 'R': (ar, gr), 'E': (ae, ge)}[which]
        return expression(which, S, T, 2, asof, N, intercept, gain, energy, previous, base)''')
new=node_text(S/'nextgen_control.py','affine_plan')
new=replace_nested(new,'expression', '''    def make_expression(which):
        intercept, gain = {'Q': (aq, gq), 'R': (ar, gr), 'E': (ae, ge)}[which]
        return expression(which, S, T, Fdim, asof, N, intercept, gain, energy_features, previous_features, base)''')
new=new.replace("= expression('Q')", "= make_expression('Q')").replace("= expression('R')", "= make_expression('R')").replace("= expression('E')", "= make_expression('E')")
header='''# Generated by generate_adapters.py; reviewed reference logic is preserved.
import time
import numpy as np
from scipy.sparse import coo_matrix, vstack, eye, diags
from control import ETA, M, EMIN, EMAX, lp_solve, features
from native import expression
'''
(R/'native_planner.py').write_text(header+'\n'+legacy+'\n'+new)
(R/'native_enhanced.py').write_text('''# Generated reference M1; only infimal convolution is native.
import numpy as np
from scipy.spatial.distance import cdist
from control import EMIN, EMAX
from nextgen_control import terminal_values, nonnegative_kernel, minimize_action
from native import inf_convolution
'''+node_text(S/'nextgen_control.py','EnhancedMarkovDP'))
(R/'native_feedback.py').write_text('''# Reference summation and tie ordering; native PL convolution.
import numpy as np
from control import EMIN, EMAX, ETA, M
from nextgen_scenarios import weighted_quantile
from nextgen_control import terminal_values, minimize_action
from native import inf_convolution
'''+node_text(S/'control.py','MarkovDP')+'\n'+node_text(S/'nextgen_control.py','WeightedMarkovDP'))
paths=[S/'control.py',S/'nextgen_control.py',R/'generate_adapters.py',R/'native_planner.py',R/'native_enhanced.py',R/'native_feedback.py']
(R/'adapter-sources.json').write_text(json.dumps({str(p.relative_to(R.parent)):hashlib.sha256(p.read_bytes()).hexdigest() for p in paths},indent=2)+'\n')
print('Generated native_planner.py and native_enhanced.py')
