# Generated by generate_adapters.py; reviewed reference logic is preserved.
import time
import numpy as np
from scipy.sparse import coo_matrix, vstack, eye, diags
from control import ETA, M, EMIN, EMAX, lp_solve, features
from native import expression

def legacy_affine_plan(net,prices,asof,E,base=None,adjust=False,affine=True,tail_price=0.,terminal=None,tail_cuts=None,daily_closed=False,solver='ipm'):
    """Node-time affine recourse. Future contracts use ONLY pre-release errors.

    Scenario states are feasible in-sample; unseen paths are projected physically.
    Future official forecast innovations are omitted from this restricted policy
    class, while actual current releases are used by the scenario producer.
    """
    S,T=net.shape;K=S*T;clock=np.arange(asof,asof+T); day0=asof//144
    blocks=clock//36-clock[0]//36;B=int(blocks.max()+1);days=clock//144-day0;D=int(days.max()+1)
    err,ema,avg=features(net)
    # a_q, a_r, a_E, g_q, g_r, g_E, emergency, delivered contract charge.
    aq=0; ar=T; ae=2*T;gq=3*T;gr=gq+2*D;ge=gr+2*B;em=ge+2*B;bill=em+K;theta=bill+K;N=theta+(S if tail_cuts else 0)
    def expr(which):
        if not affine:
            raise ValueError('Native planner adapter supports the registered affine policy only')
        energy = np.stack((err, ema), axis=2)
        previous = np.stack((avg, ema), axis=2)
        intercept, gain = {'Q': (aq, gq), 'R': (ar, gr), 'E': (ae, ge)}[which]
        return expression(which, S, T, 2, asof, N, intercept, gain, energy, previous, base)
    Q,q0=expr('Q'); R,r0=expr('R') if adjust else (Q,q0);X,x0=expr('E')
    if adjust:
        firstblock=np.tile(clock%144<36,S).astype(float)
        from scipy.sparse import diags
        keep=diags(firstblock);R=keep@Q+(eye(K)-keep)@R;r0=firstblock*q0+(1-firstblock)*r0
    shift=coo_matrix((np.ones(S*(T-1)),(np.concatenate([np.arange(s*T+1,(s+1)*T) for s in range(S)]),np.concatenate([np.arange(s*T,(s+1)*T-1) for s in range(S)]))),shape=(K,K)).tocsr()
    Delta=X-shift@X; delta0=np.zeros(K);delta0[np.arange(S)*T]=-E
    U=coo_matrix((np.ones(K),(np.arange(K),em+np.arange(K))),shape=(K,N)).tocsr()
    F=coo_matrix((np.ones(K),(np.arange(K),bill+np.arange(K))),shape=(K,N)).tocsr()
    mats=[-Q,-R,X,-X,Delta,-Delta,ETA*Delta-R-U,Delta/ETA-R-U,1.5*R-.5*Q-F,.5*R+.5*Q-F]
    rhs=[q0,r0,np.full(K,EMAX),np.full(K,-EMIN),np.full(K,ETA*M)-delta0,np.full(K,M/ETA)+delta0,
         r0-net.ravel()-ETA*delta0,r0-net.ravel()-delta0/ETA,.5*q0-1.5*r0,-.5*q0-.5*r0]
    last=np.arange(S)*T+T-1
    if terminal is not None:
        mats +=[X[last],-X[last]];rhs +=[np.full(S,terminal),np.full(S,-terminal)]
    if daily_closed:
        mids=np.flatnonzero(np.tile((clock+1)%144==0,S))
        mats +=[X[mids],-X[mids]];rhs +=[np.full(len(mids),6000.),np.full(len(mids),-6000.)]
    if tail_cuts:
        Theta=coo_matrix((np.ones(S),(np.arange(S),theta+np.arange(S))),shape=(S,N)).tocsr()
        for alpha,beta in tail_cuts:mats.append(beta*X[last]-Theta);rhs.append(np.full(S,-alpha))
    obj=np.zeros(N);obj[em:bill]=(5*prices/S).ravel();obj[bill:theta]=(prices/S).ravel()
    if tail_cuts:obj[theta:]=1/S
    obj-=tail_price*np.asarray(X[last].mean(0)).ravel()
    bounds=[(None,None)]*(3*T)+[(-10,10) if affine else (0,0)]*(2*D+4*B)+[(0,None)]*(2*K+(S if tail_cuts else 0))
    sol=lp_solve(obj,vstack(mats),np.concatenate(rhs),bounds,solver);x=sol.x
    qs=(Q@x+q0).reshape(S,T);rs=(R@x+r0).reshape(S,T);xs=(X@x).reshape(S,T)
    prev=np.c_[np.full(S,E),xs[:,:-1]];delta=xs-prev
    emer=np.maximum(net-rs+np.maximum(ETA*delta,delta/ETA),0)
    true=float(np.mean(np.sum(prices*(np.maximum(1.5*rs-.5*qs,.5*rs+.5*qs)+5*emer),axis=1))-tail_price*xs[:,-1].mean())
    if tail_cuts:true+=float(np.maximum(0,np.max([a+b*xs[:,-1] for a,b in tail_cuts],axis=0)).mean())
    return {'q':qs.mean(0),'r':rs.mean(0),'a':x[ae:ae+T],'g':x[ge:ge+2*B].reshape(B,2),
            'center':net.mean(0),'asof':asof,'lp_violation':sol.violation,'objective_gap':abs(true-sol.fun),
            'scenario_q':qs,'scenario_r':rs,'scenario_state':xs,'forecast_contract_gain':x[gq:gr],
            'all_gain':x[gq:em],
            'gain_active_columns':np.asarray(abs(vstack(mats)[:,gq:em]).sum(axis=0)).ravel()>1e-12}

def affine_plan(bundle, asof, inventory, config, base=None, adjust=False,
                tail_price=0., terminal=None, tail_cuts=None):
    started = time.perf_counter()
    net, prices, weights = (bundle[k] for k in ('net', 'prices', 'weights'))
    S, T = net.shape; K = S*T; clock = np.arange(asof, asof+T)
    if config.upper == 'legacy' and config.alpha == .2 and config.gain_bound == 10. and np.all(weights == 1/S):
        if tail_cuts and (asof+T) % 144:
            raise ValueError('Existing SDDP inventory cuts require midnight')
        answer = legacy_affine_plan(net, prices, asof, inventory, base, adjust, True, tail_price, terminal, tail_cuts)
        active = answer.pop('gain_active_columns'); gains = answer.pop('all_gain')
        answer.update({'runtime_seconds': time.perf_counter()-started,
                       'gain_active_count': int(active.sum()),
                       'gain_bound_hit_count': int(np.sum((np.abs(gains)>=10*(1-1e-6)) & active)),
                       'gain_max_abs': float(np.max(np.abs(gains[active]), initial=0)),
                       'contract_information_cutoffs': {'original': (clock//144*144).tolist(), 'effective': (clock//36*36 if adjust else clock//144*144).tolist()},
                       'future_partial_contract_completion': 'outside-core suffix fixed to nonnegative origin forecast, no tail delivery cost'})
        return answer
    blocks = clock//36-clock[0]//36; B = int(blocks.max()+1)
    days = clock//144-asof//144; D = int(days.max()+1)
    if config.upper == 'legacy':
        error = net-weights@net; ema = np.empty_like(error); avg = np.empty_like(error)
        z = np.zeros(S)
        for j in range(T):
            z = (1-config.alpha)*z+config.alpha*error[:, j]; ema[:, j] = z
            avg[:, j] = error[:, max(0, j-35):j+1].mean(1)
        energy_features = np.stack((error, ema), axis=2)
        previous_features = np.stack((avg, ema), axis=2)
    elif config.upper == 'state':
        energy_features = bundle['states'].copy()
        previous_features = energy_features.copy()
        if energy_features.shape[-1] == 4:
            # Battery state has p_(t-1); next release may use the newly disclosed p_t.
            ep = prices-bundle['forecast']['price']
            zp = np.full(S, bundle['seed'][3])
            for j in range(T):
                zp = (1-config.alpha)*zp+config.alpha*ep[:, j]
                previous_features[:, j, 2:] = np.c_[ep[:, j], zp]
            scale = max(float(np.std(bundle['history_net_error'])), 1e-8)/max(float(np.std(bundle['history_price_error'])), 1e-8)
            energy_features[:, :, 2:] *= scale; previous_features[:, :, 2:] *= scale
        energy_features -= np.einsum('s,std->td', weights, energy_features)
        previous_features -= np.einsum('s,std->td', weights, previous_features)
    else:
        raise ValueError(config.upper)
    Fdim = energy_features.shape[2]
    aq = 0; ar = T; ae = 2*T; gq = 3*T; gr = gq+Fdim*D
    ge = gr+Fdim*B; em = ge+Fdim*B; bill = em+K; theta = bill+K
    N = theta+(S if tail_cuts else 0)

    def make_expression(which):
        intercept, gain = {'Q': (aq, gq), 'R': (ar, gr), 'E': (ae, ge)}[which]
        return expression(which, S, T, Fdim, asof, N, intercept, gain, energy_features, previous_features, base)

    Q, q0 = make_expression('Q'); R, r0 = make_expression('R') if adjust else (Q, q0)
    X, _ = make_expression('E')
    if adjust:
        first = np.tile(clock % 144 < 36, S).astype(float); keep = diags(first)
        R = keep@Q+(eye(K)-keep)@R; r0 = first*q0+(1-first)*r0
    shift = coo_matrix((np.ones(S*(T-1)),
        (np.concatenate([np.arange(s*T+1, (s+1)*T) for s in range(S)]),
         np.concatenate([np.arange(s*T, (s+1)*T-1) for s in range(S)]))), shape=(K, K)).tocsr()
    Delta = X-shift@X; delta0 = np.zeros(K); delta0[np.arange(S)*T] = -inventory
    U = coo_matrix((np.ones(K), (np.arange(K), em+np.arange(K))), shape=(K, N)).tocsr()
    C = coo_matrix((np.ones(K), (np.arange(K), bill+np.arange(K))), shape=(K, N)).tocsr()
    mats = [-Q, -R, X, -X, Delta, -Delta, ETA*Delta-R-U, Delta/ETA-R-U,
            1.5*R-.5*Q-C, .5*R+.5*Q-C]
    rhs = [q0, r0, np.full(K, EMAX), np.full(K, -EMIN),
           np.full(K, ETA*M)-delta0, np.full(K, M/ETA)+delta0,
           r0-net.ravel()-ETA*delta0, r0-net.ravel()-delta0/ETA,
           .5*q0-1.5*r0, -.5*q0-.5*r0]
    last = np.arange(S)*T+T-1
    if terminal is not None:
        mats += [X[last], -X[last]]; rhs += [np.full(S, terminal), np.full(S, -terminal)]
    if tail_cuts:
        if (asof+T) % 144:
            raise ValueError('Existing inventory-only SDDP cuts require a midnight contract-reset interface')
        Theta = coo_matrix((np.ones(S), (np.arange(S), theta+np.arange(S))), shape=(S, N)).tocsr()
        for intercept, slope in tail_cuts:
            mats.append(slope*X[last]-Theta); rhs.append(np.full(S, -intercept))
    obj = np.zeros(N); obj[em:bill] = (5*prices*weights[:, None]).ravel()
    obj[bill:theta] = (prices*weights[:, None]).ravel()
    if tail_cuts:
        obj[theta:] = weights
    obj -= tail_price*np.asarray(weights@X[last]).ravel()
    bounds = [(None, None)]*(3*T)+[(-config.gain_bound, config.gain_bound)]*(Fdim*(D+2*B))+[(0, None)]*(2*K+(S if tail_cuts else 0))
    sol = lp_solve(obj, vstack(mats), np.concatenate(rhs), bounds)
    qs = (Q@sol.x+q0).reshape(S, T); rs = (R@sol.x+r0).reshape(S, T)
    xs = (X@sol.x).reshape(S, T); delta = xs-np.c_[np.full(S, inventory), xs[:, :-1]]
    emergency = np.maximum(net-rs+np.maximum(ETA*delta, delta/ETA), 0)
    bills = np.sum(prices*(np.maximum(1.5*rs-.5*qs, .5*rs+.5*qs)+5*emergency), axis=1)
    recomputed = float(weights@(bills-tail_price*xs[:, -1]))
    if tail_cuts:
        recomputed += float(weights@np.maximum(0, np.max([a+b*xs[:, -1] for a, b in tail_cuts], axis=0)))
    gains = sol.x[gq:em]; bound_hit = np.abs(gains) >= config.gain_bound*(1-1e-6)
    # Inactive root-node gains do not count toward the binding-frequency denominator.
    active_columns = np.asarray(abs(vstack(mats)[:, gq:em]).sum(axis=0)).ravel() > 1e-12
    return {'q': weights@qs, 'r': weights@rs, 'scenario_q': qs, 'scenario_r': rs,
            'scenario_state': xs, 'lp_violation': sol.violation,
            'objective_gap': abs(recomputed-sol.fun), 'objective': sol.fun,
            'runtime_seconds': time.perf_counter()-started,
            'gain_active_count': int(active_columns.sum()),
            'gain_bound_hit_count': int(np.sum(bound_hit & active_columns)),
            'gain_max_abs': float(np.max(np.abs(gains[active_columns]), initial=0)),
            'contract_information_cutoffs': {'original': (clock//144*144).tolist(),
                                             'effective': (clock//36*36 if adjust else clock//144*144).tolist()},
            'future_partial_contract_completion': 'outside-core suffix fixed to nonnegative forecast from this origin; suffix delivery costs omitted by inventory-tail truncation'}
