#include "core.hpp"
using namespace mg;
struct Result{double planned=0,increase=0,reduction=0,emcost=0,emenergy=0,spill=0,balance=0,recurrence=0,emin_seen=1e9,emax_seen=-1e9,power=0,end=0,seconds=0;int days=0;double total()const{return planned+increase+reduction+emcost;}};
const std::array<std::string,4> names{"q2","q3","q4_2","q4_3"};
Result run(const Data&a,const Forecast&f,int kind,const Config&cfg,int first,int last,const std::string&out=""){
 bool official=kind%2,variable=kind>=2;Result z;double E=6000;std::ofstream daily,trace;
 if(!out.empty()){std::filesystem::create_directories(out);daily.open(out+"/daily_"+names[kind]+".csv");trace.open(out+"/trace_"+names[kind]+".csv");daily<<std::setprecision(17)<<"day,date,planned,increase,reduction,emergency,total,initial,terminal,emergency_kwh,spill_kwh\n";trace<<std::setprecision(17)<<"day,slot,q,r,net,price,charge,discharge,emergency,spill,energy_before,energy_after\n";}
 auto clock=std::chrono::steady_clock::now();
 for(int day=first;day<=last;day++){
  bool close=day==last;double lambda=1e9;for(int t=0;t<36;t++)lambda=std::min(lambda,variable?std::max(.001,f.at(2,day,0,t)):a.tariff[t]);lambda*=cfg.lambdaFactor/eta;
  double start=E,pc=0,ic=0,rc=0,ec=0,ee=0,spill=0;auto pol=plan(a,f,day,official,variable,cfg,E,close,lambda);Scenes sc;std::vector<double>qr,obs;int active=0;
  for(int t=0;t<T;t++){
   int k=official?t/36:0;
   if(cfg.lower&&(t==0||(official&&t%36==0))){active=t;sc=scenarios(a,f,day,k,official,variable,cfg.scale);qr.clear();obs.clear();for(int u=t;u<T;u++)qr.push_back(std::max(0.,pol.q[u]+cfg.gamma*(f.net(day,k,u,official)-f.net(day,0,u,official))));}
   double q=pol.q[t],r=std::max(0.,q+cfg.gamma*(f.net(day,k,t,official)-f.net(day,0,t,official))),net=a.net(day,t),price=variable?a.x[2][day*T+t]:a.tariff[t];Act ac;
   if(cfg.lower){obs.push_back(net);double next=mpc_target(sc,qr,obs,t-active,E,close,lambda);double dl=std::max(emin,E-Dmax),du=std::min(emax,E+Cmax);if(close){dl=std::max(dl,6000-(143-t)*Cmax);du=std::min(du,6000+(143-t)*Dmax);}if(next<dl-1e-5||next>du+1e-5)throw std::runtime_error("MPC infeasible action");next=clip(next,dl,du);double delta=next-E,b=r-net-bus(delta);ac={next,0,0,0,std::max(-b,0.),std::max(b,0.),std::max(delta,0.)/eta,eta*std::max(-delta,0.)};}
   else ac=action(E,r,net,pol.res[t/6],t,close);
   double pcc=price*q,icc=1.5*price*std::max(r-q,0.),rcc=-.5*price*std::max(q-r,0.),ecc=5*price*ac.em;pc+=pcc;ic+=icc;rc+=rcc;ec+=ecc;ee+=ac.em;spill+=ac.sp;
   z.balance=std::max(z.balance,std::abs(r+ac.em+ac.d-ac.c-ac.sp-net));z.recurrence=std::max(z.recurrence,std::abs(ac.next-E-eta*ac.c+ac.d/eta));z.power=std::max(z.power,6*std::max(ac.c,ac.d));z.emin_seen=std::min({z.emin_seen,E,ac.next});z.emax_seen=std::max({z.emax_seen,E,ac.next});
   if(!out.empty())trace<<day<<','<<t<<','<<q<<','<<r<<','<<net<<','<<price<<','<<ac.c<<','<<ac.d<<','<<ac.em<<','<<ac.sp<<','<<E<<','<<ac.next<<'\n';E=ac.next;
  }
  z.planned+=pc;z.increase+=ic;z.reduction+=rc;z.emcost+=ec;z.emenergy+=ee;z.spill+=spill;z.days++;
  if(!out.empty()){daily<<day<<','<<date(day)<<','<<pc<<','<<ic<<','<<rc<<','<<ec<<','<<pc+ic+rc+ec<<','<<start<<','<<E<<','<<ee<<','<<spill<<'\n';daily.flush();if(day%30==0)std::cerr<<names[kind]<<" completed_day="<<day<<" cumulative_cost="<<z.total()<<'\n';}
 }
 z.end=E;z.seconds=std::chrono::duration<double>(std::chrono::steady_clock::now()-clock).count();if(std::abs(E-6000)>1e-5||z.emin_seen<emin-1e-5||z.emax_seen>emax+1e-5||z.power>5000+1e-5||z.balance>1e-6||z.recurrence>1e-6)throw std::runtime_error("Physical verification failed");return z;
}
void savecfg(std::string path,const Config&c,double score){std::ofstream o(path);o<<std::setprecision(17)<<c.model<<' '<<c.lower<<' '<<c.scale<<' '<<c.gamma<<' '<<c.lambdaFactor<<' '<<c.iterations<<' '<<score<<'\n';}
Config loadcfg(std::string path){Config c;std::ifstream i(path);if(!(i>>c.model>>c.lower>>c.scale>>c.gamma>>c.lambdaFactor>>c.iterations))throw std::runtime_error("Missing frozen configuration");return c;}
void gradient_test(){std::mt19937_64 g(9126);std::uniform_real_distribution<double>u(0,1);double worst=0;int count=0;for(int trial=0;trial<8;trial++){Scenes s;s.S=4;for(int k=0;k<s.S*T;k++){s.n.push_back(100+800*u(g));s.p.push_back(.1+u(g));s.shift.push_back(-100+200*u(g));}std::vector<double>q(T),r(24);for(double&x:q)x=250+500*u(g);for(double&x:r)x=2000+4000*u(g);bool close=trial%2;auto l=loss(s,q,r,6000,close,.5,.25,true);for(int k=0;k<24;k++){int j=g()%(T+24);double h=1e-4;auto a=q,b=q,c=r,d=r;if(j<T){a[j]+=h;b[j]-=h;}else{c[j-T]+=h;d[j-T]-=h;}double fd=(loss(s,a,c,6000,close,.5,.25,false).cost-loss(s,b,d,6000,close,.5,.25,false).cost)/(2*h);double ad=j<T?l.gq[j]:l.gr[j-T];worst=std::max(worst,std::abs(fd-ad));count++;}}std::cout<<std::setprecision(17)<<"gradient_comparisons,"<<count<<",max_error,"<<worst<<'\n';if(worst>1e-4)throw std::runtime_error("Gradient verification failed");}
int main(int argc,char**argv){try{if(argc<2)throw std::runtime_error("Usage: microgrid [gradient|tune|evaluate] native_dir results_dir kind");std::string cmd=argv[1];if(cmd=="gradient"){gradient_test();return 0;}if(argc!=5)throw std::runtime_error("Need native_dir results_dir kind");Data a(argv[2]);std::string out=argv[3];std::filesystem::create_directories(out);int kind=std::stoi(argv[4]);if(kind<0||kind>3)throw std::runtime_error("Invalid kind");if(cmd=="tune"){
  std::ofstream log(out+"/development_"+names[kind]+".csv");log<<std::setprecision(17)<<"model,scale,gamma,lower,total,seconds\n";double best=1e100;Config win;
  for(int model:{0,2,4}){Forecast f(a,model);for(double scale:{.75,1.,1.25})for(double gamma:(kind%2?std::vector<double>{.5,1.}:std::vector<double>{0.}))for(int lower:{0,1}){Config c;c.model=model;c.scale=scale;c.gamma=gamma;c.lower=lower;auto r=run(a,f,kind,c,21,30);log<<model<<','<<scale<<','<<gamma<<','<<lower<<','<<r.total()<<','<<r.seconds<<'\n';log.flush();if(r.total()<best){best=r.total();win=c;}}}
  savecfg(out+"/frozen_"+names[kind]+".txt",win,best);std::cout<<names[kind]<<" january_selected_cost="<<std::setprecision(17)<<best<<" model="<<win.model<<" lower="<<win.lower<<'\n';
 }else if(cmd=="evaluate"){auto c=loadcfg(out+"/frozen_"+names[kind]+".txt");Forecast f(a,c.model);auto r=run(a,f,kind,c,31,364,out);std::ofstream o(out+"/summary_"+names[kind]+".csv");o<<std::setprecision(17)<<"kind,days,total,planned,increase,reduction,emergency,emergency_kwh,spill_kwh,min_energy,max_energy,max_power,max_balance,max_recurrence,final_energy,seconds\n"<<names[kind]<<','<<r.days<<','<<r.total()<<','<<r.planned<<','<<r.increase<<','<<r.reduction<<','<<r.emcost<<','<<r.emenergy<<','<<r.spill<<','<<r.emin_seen<<','<<r.emax_seen<<','<<r.power<<','<<r.balance<<','<<r.recurrence<<','<<r.end<<','<<r.seconds<<'\n';std::cout<<names[kind]<<" COMPLETE total="<<std::setprecision(17)<<r.total()<<'\n';}else throw std::runtime_error("Unknown command");return 0;}catch(const std::exception&e){std::cerr<<"ERROR: "<<e.what()<<'\n';return 1;}}
