#include "core.hpp"
using namespace mg;
using Row=std::vector<std::string>;
std::vector<Row> csv(std::string p){std::ifstream f(p);if(!f)throw std::runtime_error("Missing "+p);std::string line;std::vector<Row>r;while(std::getline(f,line)){std::stringstream s(line);Row q;std::string t;while(std::getline(s,t,','))q.push_back(t);if(!q.empty())r.push_back(q);}return r;}
int main(int argc,char**argv){try{if(argc!=3)throw std::runtime_error("report native_dir results_dir");Data a(argv[1]);std::string dir=argv[2];const std::array<std::string,4>names{"q2","q3","q4_2","q4_3"};const std::array<double,4>expected{14093992.44543481,13630201.602693569,14930562.506556123,14427456.858625758};std::ofstream tab(dir+"/comparison.csv"),pair(dir+"/paired_daily.csv"),mon(dir+"/paired_monthly.csv"),md(dir+"/VERIFIED_RESULTS.md");tab<<std::setprecision(17)<<"case,days,baseline,new_cost,saving_yuan,saving_percent,emergency_change_percent,seconds\n";pair<<std::setprecision(17)<<"case,day,date,baseline,new_cost,saving\n";mon<<std::setprecision(17)<<"case,month,baseline,new_cost,saving_percent\n";md<<"# 原始数据验证结果\n\n以下数值由 C++ 根据原始数据及逐时轨迹计算，非语言模型估计。区间为2025-02-01至2025-12-31，共334天。首末库存均为6000 kWh；旧方案每天闭合，新方案允许跨日连续。\n\n| 设置 | 原方案费用/元 | 新方案费用/元 | 节省/元 | 降费比例 |\n|---|---:|---:|---:|---:|\n";md<<std::fixed<<std::setprecision(2);std::array<double,4>old{},now{};bool all10=true;double minsave=100,baselineerr=0;for(int k=0;k<4;k++){auto q=binary(std::filesystem::path(argv[1])/("baseline_"+names[k]+"_q.bin"),334*T),r=binary(std::filesystem::path(argv[1])/("baseline_"+names[k]+"_r.bin"),334*T),em=binary(std::filesystem::path(argv[1])/("baseline_"+names[k]+"_emergency.bin"),334*T);auto rows=csv(dir+"/daily_"+names[k]+".csv"),summary=csv(dir+"/summary_"+names[k]+".csv");if(rows.size()!=335||summary.size()!=2)throw std::runtime_error("Incomplete annual replay "+names[k]);double oldem=0;std::array<double,13>mo{},mn{};for(int j=0;j<334;j++){int d=j+31;if(std::stoi(rows[j+1][0])!=d||rows[j+1].size()!=11)throw std::runtime_error("Date alignment failed");double b=0;for(int t=0;t<T;t++){int i=j*T+t;double p=k>=2?a.x[2][d*T+t]:a.tariff[t];b+=p*(q[i]+1.5*std::max(r[i]-q[i],0.)-.5*std::max(q[i]-r[i],0.)+5*em[i]);oldem+=5*p*em[i];}double n=std::stod(rows[j+1][6]);old[k]+=b;now[k]+=n;int m=std::stoi(rows[j+1][1].substr(5,2));mo[m]+=b;mn[m]+=n;pair<<names[k]<<','<<d<<','<<rows[j+1][1]<<','<<b<<','<<n<<','<<b-n<<'\n';}if(std::abs(std::stod(rows[1][7])-6000)>1e-6||std::abs(std::stod(rows.back()[8])-6000)>1e-6)throw std::runtime_error("Unfair terminal inventory");baselineerr=std::max(baselineerr,std::abs(old[k]-expected[k]));if(std::abs(old[k]-expected[k])>1e-4)throw std::runtime_error("Baseline settlement mismatch");if(std::abs(now[k]-std::stod(summary[1][2]))>1e-5)throw std::runtime_error("New settlement mismatch");double saving=100*(old[k]-now[k])/old[k];minsave=std::min(minsave,saving);all10&=saving>=10;tab<<names[k]<<",334,"<<old[k]<<','<<now[k]<<','<<old[k]-now[k]<<','<<saving<<','<<100*(std::stod(summary[1][6])/oldem-1)<<','<<summary[1][15]<<'\n';md<<"| "<<names[k]<<" | "<<old[k]<<" | "<<now[k]<<" | "<<old[k]-now[k]<<" | "<<saving<<"% |\n";for(int m=2;m<=12;m++)mon<<names[k]<<','<<m<<','<<mo[m]<<','<<mn[m]<<','<<100*(mo[m]-mn[m])/mo[m]<<'\n';}
 md<<"\n**10%实际购电费用目标："<<(all10?"四组均通过":"尚未达到四组均下降至少10%的验收条件")<<"。** 预测误差下降和计算速度不计入费用比例。保留负收益，不替换为弱基线。\n\n## 完美信息下界\n\n此项提前知道全部实际净负荷与价格，只是乐观下界，不能作为在线执行成绩。\n\n| 价格设置 | 每日闭合下界/元 | 跨日统一终点下界/元 |\n|---|---:|---:|\n";
 std::ofstream oc(dir+"/oracle.csv");oc<<std::setprecision(17)<<"setting,daily_closed,annual_closed\n";std::array<double,2>bound;
 for(int variable=0;variable<2;variable++){double cyclic=0;std::vector<double>nall,pall,qall(334*T,0);for(int d=31;d<365;d++){std::vector<double>n(T),p(T),q(T,0);for(int t=0;t<T;t++){n[t]=a.net(d,t);p[t]=variable?a.x[2][d*T+t]:a.tariff[t];nall.push_back(n[t]);pall.push_back(p[t]);}cyclic+=dp(n,p,{1},q,6000,true,6000,0,1).value;}bound[variable]=dp(nall,pall,{1},qall,6000,true,6000,0,1).value;oc<<(variable?"variable":"fixed")<<','<<cyclic<<','<<bound[variable]<<'\n';md<<"| "<<(variable?"浮动价格":"固定分时价格")<<" | "<<cyclic<<" | "<<bound[variable]<<" |\n";}
 std::vector<double>q1net(T),q1q(T,0);for(int t=0;t<T;t++)q1net[t]=(a.dayload[t]-a.daypv[t])/6;auto q1=dp(q1net,a.tariff,{1},q1q,6000,true,6000,0,1);md<<"\n第一问确定性解："<<q1.value<<"元。\n";
 std::ofstream q1out(dir+"/q1_trace.csv");q1out<<std::setprecision(17)<<"slot,planned,charge,discharge,before,after\n";for(int t=0;t<T;t++){double delta=q1.e[t+1]-q1.e[t];q1out<<t<<','<<std::max(0.,q1net[t]+bus(delta))<<','<<std::max(delta,0.)/eta<<','<<eta*std::max(-delta,0.)<<','<<q1.e[t]<<','<<q1.e[t+1]<<'\n';}
 Forecast latest(a,0),fused(a,4);std::ofstream fa(dir+"/forecast_audit.csv");fa<<std::setprecision(17)<<"release,observations,latest_mae_kw,fused_mae_kw,mae_reduction_percent,latest_rmse_kw,fused_rmse_kw\n";md<<"\n## 预测误差的独立统计\n\n| 发布时刻 | 最新预报MAE/kW | 融合MAE/kW | MAE下降 |\n|---|---:|---:|---:|\n";double forecast0=0;for(int k=0;k<4;k++){double l=0,f=0,l2=0,f2=0;int count=0;for(int d=31;d<365;d++)for(int t=36*k;t<T;t++){double el=latest.at(3,d,k,t)-a.x[1][d*T+t],ef=fused.at(3,d,k,t)-a.x[1][d*T+t];l+=std::abs(el);f+=std::abs(ef);l2+=el*el;f2+=ef*ef;count++;}double pct=100*(l-f)/l;if(k==0)forecast0=pct;fa<<k*6<<','<<count<<','<<l/count<<','<<f/count<<','<<pct<<','<<std::sqrt(l2/count)<<','<<std::sqrt(f2/count)<<'\n';md<<"| "<<k*6<<":00 | "<<l/count<<" | "<<f/count<<" | "<<pct<<"% |\n";}
 md<<"\n这不是购电费用降幅。夜间误差较小时，还须关注绝对误差，不能只看相对比例。\n\n## 验证边界\n\n旧轨迹账单与汇总最大差为 "<<std::scientific<<baselineerr<<"元。逐时物理检查见 summary_*.csv；独立原生LP与未来信息毒化测试见 verification.csv；梯度检查见 gradient.csv。\n\n一月22—31日选择并冻结超参数，二月至十二月作因果回放。研究开发曾接触同年其他方案结果，不属于完全未接触的独立新年份测试。PWL单次凸子问题可精确求解，但非凸策略搜索及未知未来分布下的全局最优没有证明。\n";
 std::ofstream ac(dir+"/acceptance.json");ac<<std::setprecision(17)<<"{\n  \"original_data_used\": true,\n  \"days_per_case\": 334,\n  \"all_four_annual_replays_complete\": true,\n  \"native_cpp_optimization_and_simulation\": true,\n  \"baseline_settlement_max_error_yuan\": "<<baselineerr<<",\n  \"minimum_bill_saving_percent\": "<<minsave<<",\n  \"all_cases_bill_saving_at_least_10_percent\": "<<(all10?"true":"false")<<",\n  \"midnight_pv_mae_reduction_percent\": "<<forecast0<<",\n  \"independent_new_year_validation\": false,\n  \"global_optimum_proven\": false\n}\n";std::cout<<"REPORT_COMPLETE minimum_bill_saving_percent="<<minsave<<'\n';return 0;}catch(const std::exception&e){std::cerr<<"ERROR "<<e.what()<<'\n';return 1;}}
