#include "core.hpp"
#include <interfaces/highs_c_api.h>
using namespace mg;
struct LP{
 std::vector<double>cost,lo,hi,rl,ru,val;std::vector<HighsInt>start{0},index;
 int var(double c,double l,double h){cost.push_back(c);lo.push_back(l);hi.push_back(h);return (int)cost.size()-1;}
 void row(const std::vector<std::pair<int,double>>&a,double l,double h){for(auto [j,x]:a){index.push_back(j);val.push_back(x);}start.push_back(index.size());rl.push_back(l);ru.push_back(h);}
 double solve(double offset=0){void*h=Highs_create();Highs_setBoolOptionValue(h,"output_flag",0);Highs_setIntOptionValue(h,"threads",1);Highs_setDoubleOptionValue(h,"primal_feasibility_tolerance",1e-8);Highs_setDoubleOptionValue(h,"dual_feasibility_tolerance",1e-8);auto rc=Highs_passLp(h,cost.size(),rl.size(),val.size(),2,1,offset,cost.data(),lo.data(),hi.data(),rl.data(),ru.data(),start.data(),index.data(),val.data());if(rc<0||Highs_run(h)<0||Highs_getModelStatus(h)!=7){Highs_destroy(h);throw std::runtime_error("Independent HiGHS verification failed");}double result=Highs_getObjectiveValue(h);Highs_destroy(h);return result;}
};
double reference(const std::vector<double>&n,const std::vector<double>&p,const std::vector<double>&w,const std::vector<double>&q,double initial,bool closed,double target,double lambda){int N=q.size(),S=w.size();LP l;std::vector<int>delta(N),e(N),em(S*N);for(int t=0;t<N;t++)delta[t]=l.var(0,-Dmax,Cmax);for(int t=0;t<N;t++)e[t]=l.var(!closed&&t==N-1?-lambda:0,closed&&t==N-1?target:emin,closed&&t==N-1?target:emax);for(int s=0;s<S;s++)for(int t=0;t<N;t++)em[s*N+t]=l.var(5*w[s]*p[s*N+t],0,1e30);for(int t=0;t<N;t++){std::vector<std::pair<int,double>>a{{e[t],1},{delta[t],-1}};if(t)a.push_back({e[t-1],-1});l.row(a,t?0:initial,t?0:initial);for(int s=0;s<S;s++)for(double eff:{eta,1/eta})l.row({{em[s*N+t],1},{delta[t],-eff}},n[s*N+t]-q[t],1e30);}return l.solve(closed?0:6000*lambda);}
int main(int argc,char**argv){try{if(argc!=3)throw std::runtime_error("verify native_dir output_csv");Data data(argv[1]);std::ofstream o(argv[2]);o<<std::setprecision(17)<<"test,count,max_error,status\n";std::mt19937_64 gen(192606);std::uniform_real_distribution<double>u(0,1);double gap=0,phys=0;int cases=80;for(int k=0;k<cases;k++){int S=1+k%7,N=12+k%13;std::vector<double>n(S*N),p(S*N),w(S,1./S),q(N);for(auto&x:n)x=-200+1600*u(gen);for(auto&x:p)x=k%11? .01+1.5*u(gen):0.;for(auto&x:q)x=300+800*u(gen);double initial=1500+8500*u(gen),lambda=.3*u(gen);bool closed=k%2;auto r=dp(n,p,w,q,initial,closed,6000,lambda);double val=0;for(int t=0;t<N;t++){double d=r.e[t+1]-r.e[t];phys=std::max({phys,std::max(0.,emin-r.e[t+1]),std::max(0.,r.e[t+1]-emax),std::max(0.,-Dmax-d),std::max(0.,d-Cmax)});for(int s=0;s<S;s++)val+=5*w[s]*p[s*N+t]*std::max(0.,n[s*N+t]-q[t]+bus(d));}if(!closed)val-=lambda*(r.e.back()-6000);double ref=reference(n,p,w,q,initial,closed,6000,lambda);gap=std::max({gap,std::abs(val-ref),std::abs(r.value-ref)});}if(gap>1e-5||phys>1e-6)throw std::runtime_error("PWL/LP discrepancy");o<<"PWL_vs_independent_HiGHS,"<<cases<<','<<gap<<",PASS\nphysical_constraints,"<<cases<<','<<phys<<",PASS\n";o.flush();
 double causal=0;int ca=0;for(int mode:{0,2,4}){Forecast f(data,mode);for(auto [day,k]:std::vector<std::pair<int,int>>{{45,0},{173,2}}){Data poison=data;for(auto&arr:poison.x)for(int i=day*T+k*36;i<D*T;i++)arr[i]=NAN;for(int issue=day*K+k+1;issue<D*K;issue++)for(int j=0;j<24;j++)poison.raw[issue*24+j]=NAN;Forecast fp(poison,mode);for(int field=0;field<4;field++)for(int t=k*36;t<T;t++){double a=f.at(field,day,k,t),b=fp.at(field,day,k,t);if(!std::isfinite(a)||!std::isfinite(b))throw std::runtime_error("Nonfinite causal forecast");causal=std::max(causal,std::abs(a-b));}if(k==0){Config c;c.model=mode;c.gamma=.5;c.iterations=30;auto p=plan(data,f,day,true,false,c,5100,false,.25);auto pp=plan(poison,fp,day,true,false,c,5100,false,.25);for(int t=0;t<T;t++)causal=std::max(causal,std::abs(p.q[t]-pp.q[t]));}ca++;}}if(causal>1e-10)throw std::runtime_error("Future data leaked into forecast/contract");o<<"future_actual_and_unreleased_vintage_poison,"<<ca<<','<<causal<<",PASS\n";o.flush();
 double actiondiff=0;for(int k=0;k<24;k++){Scenes s;s.S=5;s.N=24;for(int i=0;i<s.S*s.N;i++){s.n.push_back(200+1000*u(gen));s.p.push_back(.1+u(gen));}std::vector<double>q(24,600),a(24),b;for(double&x:a)x=300+800*u(gen);int t=k%18;b=a;for(int i=t+1;i<24;i++)b[i]=NAN;double x=mpc_target(s,q,a,t,6000,true,.25),y=mpc_target(s,q,b,t,6000,true,.25);actiondiff=std::max(actiondiff,std::abs(x-y));}if(actiondiff>1e-10)throw std::runtime_error("Future observation leakage in MPC");o<<"future_observations_poison_MPC,24,"<<actiondiff<<",PASS\n";std::cout<<"ALL_INDEPENDENT_TESTS_PASS\n";return 0;}catch(const std::exception&e){std::cerr<<"ERROR "<<e.what()<<'\n';return 1;}}
